/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SWING;

import java.awt.Color;

/**
 *
 * @author DuongNVPH
 */
public class DangKyJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DangKyJDialog
     */
    public DangKyJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDangNhap = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        pwMatKhau1 = new javax.swing.JPasswordField();
        pwMatKhau2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Đăng ký");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đăng Ký", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 204, 204))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bạn đã có tài khoản ? ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 508, -1, -1));

        lblDangNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDangNhap.setText("Đăng Nhập");
        lblDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangNhapMouseClicked(evt);
            }
        });
        jPanel2.add(lblDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 508, -1, -1));

        txtTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTaiKhoan.setForeground(new java.awt.Color(204, 204, 204));
        txtTaiKhoan.setText("Tài khoản...");
        txtTaiKhoan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTaiKhoanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTaiKhoanFocusLost(evt);
            }
        });
        jPanel2.add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 57, 418, 32));

        txtSoDienThoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoDienThoai.setForeground(new java.awt.Color(204, 204, 204));
        txtSoDienThoai.setText("Số điện thoại...");
        txtSoDienThoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSoDienThoaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoDienThoaiFocusLost(evt);
            }
        });
        jPanel2.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 309, 418, 32));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setText("Email...");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 369, 418, 32));

        txtHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHoTen.setForeground(new java.awt.Color(204, 204, 204));
        txtHoTen.setText("Họ tên...");
        txtHoTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoTenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoTenFocusLost(evt);
            }
        });
        jPanel2.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 244, 418, 32));

        jRadioButton1.setText("Nam");
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 419, -1, -1));

        jRadioButton2.setText("Nữ");
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 419, -1, -1));

        jLabel3.setText("Giới tính :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 423, -1, -1));

        pwMatKhau1.setText("jPasswordField3");
        pwMatKhau1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwMatKhau1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwMatKhau1FocusLost(evt);
            }
        });
        jPanel2.add(pwMatKhau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 115, 418, 33));

        pwMatKhau2.setText("jPasswordField4");
        pwMatKhau2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwMatKhau2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwMatKhau2FocusLost(evt);
            }
        });
        jPanel2.add(pwMatKhau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 176, 418, 35));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Đăng ký");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 497, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 480, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangNhapMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.dispose();
            new DangNhapJDialog(null,true).setVisible(true); 
        }
    }//GEN-LAST:event_lblDangNhapMouseClicked

    private void txtTaiKhoanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTaiKhoanFocusGained
        // TODO add your handling code here:
        if (txtTaiKhoan.getText().equals("Tài khoản...")) {
            txtTaiKhoan.setText("");
        }
        txtTaiKhoan.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTaiKhoanFocusGained

    private void txtTaiKhoanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTaiKhoanFocusLost
        // TODO add your handling code here:
        if (txtTaiKhoan.getText().equals("")) {
            txtTaiKhoan.setText("Tài khoản...");
        }else{
            txtTaiKhoan.setForeground(Color.BLACK);
        }
        txtTaiKhoan.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_txtTaiKhoanFocusLost

    private void txtSoDienThoaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoDienThoaiFocusGained
        // TODO add your handling code here:
        if (txtSoDienThoai.getText().equals("Số điện thoại...")) {
            txtSoDienThoai.setText("");
        }else{
            txtSoDienThoai.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSoDienThoaiFocusGained

    private void txtSoDienThoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoDienThoaiFocusLost
        // TODO add your handling code here:
        if (txtSoDienThoai.getText().equals("")) {
            txtSoDienThoai.setText("Số điện thoại...");
        }else{
            txtSoDienThoai.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtSoDienThoaiFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        if (txtEmail.getText().equals("Email...")) {
            txtEmail.setText("");
        }else{
            txtEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Email...");
        }else{
            txtEmail.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtHoTenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoTenFocusGained
        // TODO add your handling code here:
        if (txtHoTen.getText().equals("Họ tên...")) {
            txtHoTen.setText("");
        }else{
            txtHoTen.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtHoTenFocusGained

    private void txtHoTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoTenFocusLost
        // TODO add your handling code here:
        if (txtHoTen.getText().equals("")) {
            txtHoTen.setText("Họ tên...");
        }else{
            txtHoTen.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtHoTenFocusLost

    private void pwMatKhau1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwMatKhau1FocusGained
        // TODO add your handling code here:
        if (pwMatKhau1.getText().equals("jPasswordField3")) {
            pwMatKhau1.setText("");
        }
    }//GEN-LAST:event_pwMatKhau1FocusGained

    private void pwMatKhau1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwMatKhau1FocusLost
        // TODO add your handling code here:
        if (pwMatKhau1.getText().equals("")) {
            pwMatKhau1.setText("jPasswordField3");
        }
    }//GEN-LAST:event_pwMatKhau1FocusLost

    private void pwMatKhau2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwMatKhau2FocusGained
        // TODO add your handling code here:
        if (pwMatKhau2.getText().equals("jPasswordField4")) {
            pwMatKhau2.setText("");
        }
    }//GEN-LAST:event_pwMatKhau2FocusGained

    private void pwMatKhau2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwMatKhau2FocusLost
        // TODO add your handling code here:
        if (pwMatKhau2.getText().equals("")) {
            pwMatKhau2.setText("jPasswordField4");
        }
    }//GEN-LAST:event_pwMatKhau2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangKyJDialog dialog = new DangKyJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JPasswordField pwMatKhau1;
    private javax.swing.JPasswordField pwMatKhau2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
    
    
    void init(){
        setLocationRelativeTo(null);
         setFocusable(true);
    }


}
